name: 一次性同步国外镜像
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 登录阿里云ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALI_REGISTRY }}
          username: ${{ secrets.ALI_USER }}
          password: ${{ secrets.ALI_PASSWORD }}

      - name: 同步 mysql-ndb-operator
        if: false
        run: |
          docker pull container-registry.oracle.com/mysql/community-ndb-operator:9.1.0-1.6.0
          docker tag container-registry.oracle.com/mysql/community-ndb-operator:9.1.0-1.6.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/community-ndb-operator:9.1.0-1.6.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/community-ndb-operator:9.1.0-1.6.0

      - name: 同步 community-cluster
        if: false
        run: |
          docker pull container-registry.oracle.com/mysql/community-cluster:9.1.0
          docker tag container-registry.oracle.com/mysql/community-cluster:9.1.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/community-cluster:9.1.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/community-cluster:9.1.0

      - name: 同步 netshoot
        if: false
        run: |
          docker pull nicolaka/netshoot:latest
          docker tag nicolaka/netshoot:latest \
          ${{ secrets.ALI_REGISTRY }}/liutools/netshoot:latest
          docker push ${{ secrets.ALI_REGISTRY }}/liutools/netshoot:latest

      - name: 同步 rabbitmq-operator
        if: false
        run: |
          docker pull ghcr.io/rabbitmq/cluster-operator:2.20.1
          docker tag ghcr.io/rabbitmq/cluster-operator:2.20.1 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/rabbitmq-operator:2.20.1
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/rabbitmq-operator:2.20.1

      - name: 同步 rabbitmq
        if: false
        run: |
          docker pull rabbitmq:3.9-management
          docker tag rabbitmq:3.9-management \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/rabbitmq:3.9-management
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/rabbitmq:3.9-management

      - name: 同步 ZooKeeper
        if: false
        run: |
          docker pull docker.io/bitnamilegacy/zookeeper:3.9.3-debian-12-r21
          docker tag docker.io/bitnamilegacy/zookeeper:3.9.3-debian-12-r21 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/zookeeper:3.9.3-debian-12-r21
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/zookeeper:3.9.3-debian-12-r21
      - name: 同步 kafka
        if: false
        run: |
          docker pull docker.io/bitnamilegacy/kafka:3.3.2-debian-11-r11
          docker tag docker.io/bitnamilegacy/kafka:3.3.2-debian-11-r11 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/kafka:3.3.2-debian-11-r11
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/kafka:3.3.2-debian-11-r11

      - name: 同步 alertmanager
        if: false
        run: |
          docker pull quay.io/prometheus/alertmanager:v0.28.1
          docker tag quay.io/prometheus/alertmanager:v0.28.1 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/alertmanager:v0.28.1
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/alertmanager:v0.28.1

      - name: 同步 blackbox-exporter
        if: false
        run: |
          docker pull quay.io/prometheus/blackbox-exporter:v0.27.0
          docker tag quay.io/prometheus/blackbox-exporter:v0.27.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/blackbox-exporter:v0.27.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/blackbox-exporter:v0.27.0

      - name: 同步 configmap-reload
        if: false
        run: |
          docker pull ghcr.io/jimmidyson/configmap-reload:v0.15.0
          docker tag ghcr.io/jimmidyson/configmap-reload:v0.15.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/configmap-reload:v0.15.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/configmap-reload:v0.15.0

      - name: 同步 kube-rbac-proxy
        if: false
        run: |
          docker pull quay.io/brancz/kube-rbac-proxy:v0.19.1
          docker tag quay.io/brancz/kube-rbac-proxy:v0.19.1 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/kube-rbac-proxy:v0.19.1
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/kube-rbac-proxy:v0.19.1

      - name: 同步 grafana
        if: false
        run: |
          docker pull grafana/grafana:12.1.0
          docker tag grafana/grafana:12.1.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/grafana:12.1.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/grafana:12.1.0

      - name: 同步 kube-state-metrics
        if: false
        run: |
          docker pull registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.16.0
          docker tag registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.16.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/kube-state-metrics:v2.16.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/kube-state-metrics:v2.16.0

      - name: 同步 node-exporter
        if: false
        run: |
          docker pull quay.io/prometheus/node-exporter:v1.9.1
          docker tag quay.io/prometheus/node-exporter:v1.9.1 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/node-exporter:v1.9.1
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/node-exporter:v1.9.1

      - name: 同步 prometheus-adapter
        if: false
        run: |
          docker pull registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.12.0
          docker tag registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.12.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus-adapter:v0.12.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus-adapter:v0.12.0

      - name: 同步 prometheus-operator
        if: false
        run: |
          docker pull quay.io/prometheus-operator/prometheus-operator:v0.85.0
          docker tag quay.io/prometheus-operator/prometheus-operator:v0.85.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus-operator:v0.85.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus-operator:v0.85.0

      - name: 同步 prometheus
        if: false
        run: |
          docker pull quay.io/prometheus/prometheus:v3.5.0
          docker tag quay.io/prometheus/prometheus:v3.5.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus:v3.5.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus:v3.5.0

       - name: 同步 prometheus-config-reloader
        run: |
          docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.85.0
          docker tag quay.io/prometheus-operator/prometheus-config-reloader:v0.85.0 \
          ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus-config-reloader:v3.5.0
          docker push ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/prometheus-config-reloader:v3.5.0
        

          
          
